kind: Service
apiVersion: v1
metadata:
  name: node-js-90-multiports
spec:
  selector:
    name: node-js-90
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9376
    - name: https
      protocol: TCP
      port: 443
      targetPort: 9377
