apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    # nodes labels--kubectl get nodes --show-labels
    kubernetes.io/hostname: kube-node-3
