apiVersion: v1
kind: Pod
metadata:
  name: nginx-gluster-pod
spec:
  restartPolicy: Always
  containers:
  - name: nginx-gluster-pod
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pv
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: pv
    persistentVolumeClaim:
      claimName: pvc01
