apiVersion: v1
kind: Pod
metadata:
  name: projected-volume-test
spec:
  containers:
  - name: projected-volume-test
    image: busybox
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: projected-volume
      readOnly: true
      mountPath: "/projected-volume"
  volumes:
  - name: projected-volume
    projected:
      sources:
      - secret:
          name: user
      - secret:
          name: pass
