apiVersion: v1
kind: Pod
metadata:
  name: registry-secret
spec:
  containers:
  - name: registry-secret
    image: harbor.zntest.com/library/busybox
    args:
    - sleep
    - "86400"
  imagePullSecrets:
  - name: harbor-secret
  nodeName: kube-node-2
