apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-exec
spec:
  containers:
  - name: liveness-probe-exec
    image: busybox
    args:
    - /bin/sh
    - -c
    - echo "hello">/tmp/healthy;sleep 30;rm -rf /tmp/healthy;sleep 600;
    livenessProbe:
      exec: 
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
