apiVersion: v1
kind: Pod
metadata:
  name: liveness-probe-httpget
spec:
  containers:
  - name: liveness-probe-httpget
    image: nginx
    livenessProbe:
      httpGet: 
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
