apiVersion: v1
kind: Pod
metadata:
  name: init-containers
spec:
  containers:
  - name: init-container1
    image: nginx
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: init-container2
    image: busybox
    args:
    - wget
    - -O
    - /workdir/index.html
    - www.baidu.com
    volumeMounts:
    - name: workdir
      mountPath: /workdir
  volumes:
  - name: workdir
    emptyDir: {} 
