apiVersion: v1
kind: Pod
metadata:
  name: cmd-arg-shell
spec:
  containers:
    - name: cmd-arg-shell
      image: busybox
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh" ]
      args: ["-c","ls -l | wc -l"]
  restartPolicy: Never
# command is sh
