apiVersion: v1
kind: Pod
metadata:
  name: volume-secret-pod
spec:
  containers:
    - name: volume-secret-con
      image: busybox
      imagePullPolicy: IfNotPresent
      command: [ "ls" ]
      args: 
      - "/etc/"
      volumeMounts:
      - name: secret-vol
        mountPath: /etc
  volumes:
  - name: secret-vol
    secret:
      secretName: test-secret
 
  restartPolicy: Never
# env value from pod field
