apiVersion: v1
kind: Pod
metadata:
  name: env-secret-keyref-pod
spec:
  containers:
    - name: env-secret-keyref-con
      image: busybox
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh" ]
      args: 
      - "-c"
      - "printenv USERNAME"
      env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: test-secret
            key: username
 
  restartPolicy: Never
# env value from secret
